//Network
export const NETWORK_RESET = 'NETWORK_RESET';
export const UPDATE_NETWORK_CONNECTION = 'UPDATE_NETWORK_CONNECTION';

//LoginScreen
export const INPUT_USERNAME = 'INPUT_USERNAME';
export const INPUT_PASSWORD = 'INPUT_PASSWORD';
export const LOGIN_RESET = 'LOGIN_RESET';

//RegisterScreen
export const INPUT_REGISTER_USERNAME = 'INPUT_REGISTER_USERNAME';
export const INPUT_REGISTER_PASSWORD = 'INPUT_REGISTER_PASSWORD';
export const INPUT_NAME = 'INPUT_NAME';
export const INPUT_CONFIRM_PASSWORD = 'INPUT_CONFIRM_PASSWORD';
export const INPUT_EMAIL = 'INPUT_EMAIL';
export const INPUT_PHONE_NO = 'INPUT_PHONE_NO';
export const INPUT_COMAPANY = 'INPUT_COMAPANY';
export const REGISTER_RESET = 'REGISTER_RESET';

//UserInfoScreen
export const INPUT_USERINFO_NAME = 'INPUT_USERINFO_NAME';
export const INPUT_USERINFO_TRUCKNO = 'INPUT_USERINFO_TRUCKNO';
export const INPUT_USERINFO_COMPANY = 'INPUT_USERINFO_COMPANY';
export const INPUT_USERINFO_PHONE_NUMBER = 'INPUT_USERINFO_PHONE_NUMBER';
export const UPDATE_USERINFO = 'UPDATE_USERINFO';
export const INPUT_USERINFO_RESET = 'INPUT_USERINFO_RESET';

//Auth
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const SPLASH_SCREEN_START = 'SPLASH_SCREEN_START';
export const SET_NO_ORDER_FLAG = 'SET_NO_ORDER_FLAG';
export const SET_IS_TOKEN_EXPIRED_FLAG = 'SET_IS_TOKEN_EXPIRED_FLAG';
export const SET_NO_PLATE_NUM_FLAG = 'SET_NO_PLATE_NUM_FLAG ';
export const KILL_APP_RELAUNCH = 'KILL_APP_RELAUNCH';

//Languge
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const LANGUAGE_RESET = 'LANGUAGE_RESET';

//User
export const SET_USER_MODEL = 'SET_USER_MODEL';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_TRUCK_NO = 'SET_TRUCK_NO';
export const SET_PHONE_NO = 'SET_PHONE_NO';
export const RESET_USER_MODEL = 'RESET_USER_MODEL';

//Manifest
export const UPDATE_LAST_SYNC_DATE = 'UPDATE_LAST_SYNC_DATE';
export const RESET_LAST_SYNC_DATE = 'RESET_LAST_SYNC_DATE';

//Location
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';

//Job List
export const UPDATE_JOBLIST_FILTER_TYPE = 'UPDATE_JOBLIST_FILTER_TYPE';
export const JOBLIST_FILTER_TYPE_RESET = 'JOBLIST_FILTER_TYPE_RESET';
export const SET_IS_SHOW_FILTER_MODAL = 'SET_IS_SHOW_FILTER_MODAL';
export const SET_FILTER_SUCCESS_MSG = 'SET_FILTER_SUCCESS_MSG';
export const SET_JOBLIST_REFRESH = 'SET_JOBLIST_REFRESH';
export const SET_TOTAL_JOB_NUM = 'SET_TOTAL_JOB_NUM';
export const SET_PENDING_JOB_NUM = 'SET_PENDING_JOB_NUM';
export const SET_COMPLETED_JOB_NUM = 'SET_COMPLETED_JOB_NUM';
export const SET_FAILED_JOB_NUM = 'SET_FAILED_JOB_NUM';

//Photo
export const SET_PENDING_PHOTO = 'SET_PENDING_PHOTO';
export const ADD_PENDING_PHOTO = 'ADD_PENDING_PHOTO';
export const DELETE_PENDING_PHOTO = 'DELETE_PENDING_PHOTO';

//AddOrderItemDialog
export const INPUT_PRODUCT_NAME = 'INPUT_PRODUCT_NAME';
export const INPUT_UOM = 'INPUT_UOM';
export const INPUT_QUANTITY = 'INPUT_QUANTITY';
export const ORDER_ITEM_RESET = 'ORDER_ITEM_RESET';
export const UPDATE_ORDER_ITEM = 'UPDATE_ORDER_ITEM';

//Login Modal
export const SET_IS_SHOW_LOGIN_MODAL = 'SET_IS_SHOW_LOGIN_MODAL';
export const SET_LOGIN_MODAL_ALERT_MSG = 'SET_LOGIN_MODAL_ALERT_MSG';
export const LOGIN_MODAL_RESET = 'LOGIN_MODAL_RESET';

//Job Transfer Modal
export const SET_RECEIVER_TRANSFER_DATA = 'SET_RECEIVER_TRANSFER_DATA';
export const SET_SENDER_TRANSFER_DATA = 'SET_SENDER_TRANSFER_DATA';
export const SET_CONNECTED_DEIVCE = 'SET_CONNECTED_DEIVCE';
export const SET_IS_DISCONNECTED_FLAG = 'SET_IS_DISCONNECTED_FLAG';
export const SET_IS_LOSS_CONNECTION_MODAL_VISIBLE =
  'SET_IS_LOSS_CONNECTION_MODAL_VISIBLE';
export const SET_IS_SENDER_CONNECTED = 'SET_IS_SENDER_CONNECTED';
export const SET_IS_CONFRIM_JOB_TRANSFER = 'SET_IS_CONFRIM_JOB_TRANSFER';
export const SET_IS_CANCEL_JOB_TRANSFER = 'SET_IS_CANCEL_JOB_TRANSFER';
export const SET_IS_ACCEPT_TRANSFER = 'SET_IS_ACCEPT_JOB_TRANSFER';
export const SET_JOB_TRANSFER_ACTION = 'SET_JOB_TRANSFER_ACTION';
export const UPDATE_JOBS_DATA = 'UPDATE_JOBS_DATA';
export const UPDATE_SELECTED_JOBS_DATA = 'UPDATE_SELECTED_JOBS_DATA';
export const UPDATE_IS_RECEIVE_END = 'UPDATE_IS_RECEIVE_END';
export const UPDATE_RECEIVE_SELECTED_JOB_ID = 'UPDATE_RECEIVE_SELECTED_JOB_ID';
export const UPDATE_RECEIVE_CANCEL_SELECTED_JOB_ID =
  'UPDATE_RECEIVE_CANCEL_SELECTED_JOB_ID';
export const RESET_SELECTED_AND_CANCEL_SELECT_JOB_ID =
  'RESET_SELECTED_AND_CANCEL_SELECT_JOB_ID';
export const TRANSFER_DATA_RESET = 'TRANSFER_DATA_RESET';
export const SET_IS_DONE_TRANSFER = 'SET_IS_DONE_TRANSFER';
export const SET_IS_DISCONNECT_TRIGGER = 'SET_IS_DISCONNECT_TRIGGER';
export const SET_IS_BT_HAS_SIGNAL = 'SET_IS_BT_HAS_SIGNAL';
export const SET_IS_BT_CONNECTION_ERROR = 'SET_IS_BT_CONNECTION_ERROR';

//SKU
export const UPDATE_SKU_ORDER_ITEMS = 'UPDATE_SKU_ORDER_ITEMS';
export const DELETE_SKU_ORDER_ITEMS = 'DELETE_SKU_ORDER_ITEMS';

export const SET_JOB_TRANSFER_SELECTED_ITEMS = 'SET_JOB_TRANSFER_SELECTED_ITEMS';
export const SET_JOB_TRANSFER_STATUS = 'SET_JOB_TRANSFER_STATUS';
