require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ePOD' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

#  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
#    'BarcodeDetectorMLKit'
#  ]
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-camera-roll/camera-roll'

  target 'ePODTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1'})
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ePOD-tvOS' do
  # Pods for ePOD-tvOS

  target 'ePOD-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
